### ISSUE TITLE
Check for derived in tally sum but not in sum_sq

### ISSUE THREAD

**Issue by lindsayad** [mit-crpg/openmc#1010]
Is there any good reason why we check `self.derived` [here](https://github.com/mit-crpg/openmc/blob/develop/openmc/tallies.py#L211)? We don't perform that check for `mean` or `sum_sq`. This is troublesome when creating a new tally with `get_slice` for example.

**Comment by paulromano** [comment]
I think the logic behind it is that only real tallies have a `sum` attribute because that it corresponds directly to what OpenMC is actually accumulating during transport. For a derived tally, it doesn't make sense to have a "sum" because it doesn't reflect a tally for which realizations were actually accumulated. However, a derived tally can have a mean that is determined in relation to the original tallies it was derived from. I'm not sure why `sum_sq` doesn't have a similar check because the same argument applies as for `sum`.

What is the specific problem that you are running into with `get_slice`?

**Comment by lindsayad** [comment]
"troublesome" was the wrong word to use... I wasn't thinking completely about my problem; `mean` contains all the information I need.

The logic makes sense to me. Maybe I'll submit a PR with the `derived` check added for `sum_sq` and then consider this a closed issue.
