### ISSUE TITLE
 Question about Installation of the Newest Version of OpenMC

### ISSUE THREAD

**Issue by Johnny0719** [mit-crpg/openmc#519]
Hi, may I ask a question about installation of the newest version of OpenMC? 

When I was trying to install the newest version of OpenMC, I met a bunch of errors saying “There is no specific subroutine for the generic 'h5dread_f' at (1)”. 

I used to successfully installed a previous version of OpenMC with hdf5 (in September), but it seems not working for the newest version.

I did the following steps:

1) git clone https://github.com/mit-crpg/openmc.git
2) cd openmc
3) export FC=gfortran HDF5_DIR
	(hdf5-1.8.15 has been installed in my laptop since September)
4) mkdir build && cd build
5) cmake ..
6) make

Thanks a lot!

**Comment by wbinventor** [comment]
@Johnny0719 I think the build instructions changed a bit since September. In particular, see if the following fixes your issue:

```bash
> rm -rf build
> mkdir build
> cd build
> FC=gfortran HDF5_DIR=/home/johnny/hdf5_install cmake ..
> make
> sudo make install
```

Note that if you HDF5 with MPI, you should change "FC=gfortran" to "FC=mpif90".

Unfortunately, these updated installation instructions are not included in the documentation at the moment. The website is only updated when we create official "release" versions of the code. We are preparing to release v0.7.1 in the next few days and the website will be updated with up-to-date instructions. Perhaps we need to do a better job publishing documentation for the "developmental" version of the code in addition to the "release" version, especially since the "develop" branch is the default one on GitHub.

**Comment by Johnny0719** [comment]
Yes this works! Thanks a lot!!

**Comment by wbinventor** [comment]
Excellent! I'm glad to hear that. Thanks for reporting this @Johnny0719!
