### ISSUE TITLE
Units on division of scores with tally arithmetic

### ISSUE THREAD

**Issue by paulromano** [mit-crpg/openmc#549]
When two scores are divided that have the same units, currently you get a derived score with the same units as the two scores, e.g. if you have an absorption score divided by another absorption score, the resulting quantity will be shown with units of absorption rather than absorption / absorption. This can be seen in Out[27] in the [tally arithmetic notebook](http://openmc.readthedocs.org/en/latest/pythonapi/examples/tally-arithmetic.html). This would be the correct behavior for addition and subtraction but for multiplication and division (and I suppose for exponentiation), having the same units doesn't mean the derived score should have the same units. As I understand, this should be a fairly trivial fix with @samuelshaner's new hybrid_product capability.

**Comment by samuelshaner** [comment]
Each value in a Tally will have "units" that describe the scores, nuclides, and filters used to produce the value. Currently, the units of a derived tally will depend on type of product performed, entrywise or tensor, over the scores, nuclides, and filters:

* **Entrywise Product**: An entrywise product is only performed on values that have the same units. For instances, cell [27] of tally-arithmetic.ipynb performs an entrywise product across scores, nuclides, and filters. The units from an entrywise product will always be the units of the common score/nuclide/filter. 
* **Tensor Product**: A tensor product is performed on values irregardless of units. For instances, cell [30] of tally-arithmetic.ipynb performs a tensor product across scores and an entrywise product across nuclides and filters. The units from a tensor product will be `(units left) binary_op (units right)`.

As @paulromano alluded to, it would be better if the units took into account the operation being performed instead of the type of product, so:

* **+ or -**: If the units of the operands are the same, the units of the derived tally are the common units. If the units are different, the units of the derived tally are `(units left) binary_op (units right)`.
* **\* or /**: The units of the derived tally are `(units left) binary_op (units right)`.
* **^**: The units of the derived tally are `(units left) binary_op (exponent)`.

I'll submit a PR with these changes sometime this week.
