### ISSUE TITLE
mesh tally indexing in python api error

### ISSUE THREAD

**Issue by nelsonag** [mit-crpg/openmc#624]
Something happened to the indexing of mesh tallies in the python API.  For example, see this result, obtained by the examples/pincell problem run as is:
![screenshot from 2016-04-09 13-01-52](https://cloud.githubusercontent.com/assets/1037107/14405043/3fe8919e-fe53-11e5-8c61-698a0255e471.png)

I get the same result with direct access to the api (like in the [pyapi post processing example](http://openmc.readthedocs.org/en/latest/pythonapi/examples/post-processing.html)).

Thoughts?

**Comment by wbinventor** [comment]
Which version of h5py are you using?

**Comment by nelsonag** [comment]
@wbinventor 2.6.0

**Comment by wbinventor** [comment]
Does this issue appear with v2.5? We've seen some odd bugs with h5py v2.6. I'd be surprised if there really is a new issue with our mesh tallies since 1) I don't believe that anything related to mesh tallies has changed in a long time and 2) our test suite *should* have picked up any obvious bugs such as what you are seeing anyway.

**Comment by nelsonag** [comment]
Interesting point.  Let me revert and get back to you

**Comment by nelsonag** [comment]
Reverting back to 2.5.0 worked, looks like i've got another job for anaconda...

**Comment by wbinventor** [comment]
Good to hear. Seems like this is really an issue for the h5py team then, correct?

**Comment by paulromano** [comment]
Yes, I believe it is the [same issue](https://github.com/h5py/h5py/issues/698) that caused regression tests to fail.
