### ISSUE TITLE
Improve XML parsing performance for distribmats

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/openmc#796]
I've been modeling some PWR benchmarks with pin-wise depleted isotopics (400+ nuclides per pin) using @cjosey's OpenDeplete, which makes use of OpenMC's distribmats functionality. This has exposed a bottleneck in the XML parser when reading in large "materials.xml" files. OpenMC hangs at this stage for about 2 minutes for a single PWR assembly problem (download the inputs [here](https://www.dropbox.com/sh/jn33rl0v1uk35mu/AABmFP353TSeGuQmwN_G3cXga?dl=0)):

```bash
 Reading cross sections XML file...
```

Furthermore, the performance degradation appears to scale non-linearly with the size of the XML inputs. As a reference point, it took ~20 hours to parse the 2.8 million line "materials.xml" file (135 MB) for a pin-wise depleted SMR model with ~10,000 fuel pins.

**Comment by paulromano** [comment]
My initial plan is to replace FoX with the [RapidXml C++ library](http://rapidxml.sourceforge.net/) (unless anyone has a better suggestion) and expose a few key functions that can be called via Fortran/C interoperability.

**Comment by paulromano** [comment]
I made really good progress on this yesterday and today. I ended up using [pugixml](http://pugixml.org/) which is just as fast as RapidXml, actively maintained, and has a more intuitive API. I created an example which reads all nuclide densities from a materials.xml file into an array of the following type
```Fortran
type :: Material
  real(8), allocatable :: density(:)
end type
```
To read and store all the nuclide densities in a 22 MB materials.xml file took 0.472 seconds.

Now I just need to go through and refactor the 5000+ lines in input_xml.F90 to use the new interface... Expect a PR next week.

**Comment by cjosey** [comment]
While XML is fine and all, would it be better to use an HDF5 materials file (or perhaps all the inputs)?  We can parallel write an HDF5 file.  The downside is that either we'd have to support both XML and HDF5 as options, or provide a converter script to convert XML to HDF5.

**Comment by nelsonag** [comment]
Seems like that last question by @cjosey could be re-characterized as "should we even have ASCII/XML input anymore or should we only support the Python API for model entry?"

While I'd love the removal of all the XML baggage, I still vote for some form of ASCII entry. I often rely on the ability to get in there and tweak individual items in the XML and rerunning instead of via the python. On the python side you then have to worry if you're tweaking a variable that is used in downstream parts of the script or not, and it just adds overhead. But that's my .02$, I know I'm more curmudgeonly than the rest

**Comment by wbinventor** [comment]
First, it sounds like pugixml is much faster than Fox, so I fully support migrating to it.

As for HDF5 support, I agree with both @cjosey and @nelsonag. I don't think it makes much sense to write large ASCII files full of floating point data (i.e., depleted nuclide number densities). Not only is this incredibly inefficient in terms of storage, as @cjosey points out it forfeits the potential to use parallel I/O. While this is probably not an issue for the relatively small (22MB) "materials.xml" for my depleted 2x2 benchmarks, or even the slightly larger (100+ MB) file for the SMR model, the problem will grow 3-4 orders of magnitude harder with axially- and radially-discretized depletion zones. In my mind, we will absolutely need to use binary inputs for depleted materials in the long run.

That said, I agree with @nelsonag and think we should continue to support XML inputs for their human readability. The vast majority of users are not likely to model insanely large depleted material inputs in the near to intermediate term. Switching to an all-HDF5 input format would be far more burdensome than the benefits it would provide.

Hence, while I think we should support HDF5 material inputs soon, it is still valuable to optimize our XML parser. These efforts will benefit all users, not just those of us looking ahead to model large challenge problems.

**Comment by cjosey** [comment]
I didn't suggest the removal of XML.  I saw two options that didn't substantially reduce user-friendliness: an alternative HDF5 materials file or using XML as an intermediate format.

The first would increase the complexity of the Fortran code and still require maintaining an XML library in the codebase.  It would be the most current-user friendly.

The second option would offload much of the complexity from the Fortran into the Python.  The user then has three options: pyAPI -> HDF5 -> OpenMC, pyAPI -> XML -> HDF5 -> OpenMC, or user-defined XML -> HDF5 -> OpenMC.  XML would have to be preprocessed if exported into an environment without Python, but the intermediate representation would always be available.

Regardless, just thought I'd bring it up while changes were being discussed.  Input files are not currently limiting OpenMC's maximum simulation size, but they will eventually.

**Comment by paulromano** [comment]
Ultimately I'd like to be able to set/modify nuclide densities in memory which would obviate a lot of these concerns. In the meantime, I can attest that there are many users who like having ASCII inputs. I don't think anyone is against improving our XML parsing, so that is what I am currently working on given the terrible performance of FoX. I wouldn't be opposed to having an HDF5 option too.

One design decision as I'm going through how OpenMC handles XML: right now OpenMC allows one to specify properties via attributes or elements, e.g., the following inputs both work:
```XML
<material id="5">
  ...
```
or
```XML
<material>
  <id>5</id>
  ...
```
We might want to consider being a little more restrictive (i.e. only accepting one of the above) because 1) it may also help improve XML read performance if we don't have to constantly check whether something appears is an attribute or and element and 2) as more people adopt the Python API, there is a reduced likelihood that XML inputs would deviate from what the API writes. Thoughts?

**Comment by wbinventor** [comment]
Closing with #814.
