### ISSUE TITLE
O18 cross-section in Python API but not in NNDC data

### ISSUE THREAD

**Issue by RonRahaman** [mit-crpg/openmc#798]
Last time I downloaded the NNDC data (using the `openmc-get-nndc-data` script) I noticed that I didn't get the O18 cross-sections:
```
rahaman@calcifer:~/openmc_cross_sections/nndc_hdf5$ grep "O[[:digit:]]" cross_sections.xml 
    <library materials="O16" path="O16.h5" type="neutron" />
    <library materials="O17" path="O17.h5" type="neutron" />
    <library materials="c_O_in_UO2" path="c_O_in_UO2.h5" type="thermal" />
    <library materials="c_U_in_UO2" path="c_U_in_UO2.h5" type="thermal" />
```

I only noticed this because the Python API includes O18 in the list of isotopes (see `openmc/data/data.py`).  So after I run a script like `examples/python/pincell/build-xml.py`, which calls add_element('O'), the resultant materials.xml file contains O18, and I get a runtime error when I try to use it in openmc.  

Am I downloading the correct cross section data?

**Comment by RonRahaman** [comment]
BTW, I'm not blocked by this issue, since I can manually edit the materials.xml file to delete O18.

**Comment by paulromano** [comment]
There is some element trickery that goes on behind the scenes. We recently changed OpenMC to only support natural elements in the Python API. So, when you add an element to a `Material`, at the time it is being written to XML, it will expand the natural element into its isotopic constituents based on their known natural abundances. This is supposed to happen in a smart way -- if you specified `Materials.cross_sections` (telling OpenMC where to find your cross_sections.xml), it will use that listing to make sure it doesn't add isotopes that you don't have cross sections for, like O18 in this case. If you didn't specify `Materials.cross_sections`, it falls back to checking your `OPENMC_CROSS_SECTIONS` environment variable. If that is not set, then it simply just adds all isotopes irrespective of whether they exist in your cross section library or not (since it has no way of knowing).

**Comment by RonRahaman** [comment]
Thanks, Paul.  I was running build-xml.py inside my IDE, so OPENMC_CROSS_SECTIONS wasn't defined there.  When I run build_xml.py in the shell, where OPENMC_CROSS_SECTIONS is defined, the script produces a compatable materials.xml.
