### ISSUE TITLE
cmake 2.8.12.2 / GNU Make 3.81 failed building libopenmc

### ISSUE THREAD

**Issue by GiudGiud** [mit-crpg/openmc#906]
I got a wall of "undefined reference to ..." starting with "undefined reference to `std::string::c_str() const'" in the "build target libopenmc" step.
Interestingly, reverting cmake_minimum_required(VERSION 2.8.12 FATAL_ERROR) to cmake_minimum_required(VERSION 2.8 FATAL_ERROR) in CMakeLists.txt removes the problem. I found that out while reverting commits from the C API to pinpoint the problem. This change comes in commit bb6adfca2ada46d820f31674c6372df9a5247ec0. 
Same issue and same small fix on nsecluster and my workstation. 

I updated to cmake 3.9, with no other changes, and the issue disappeared.

**Comment by paulromano** [comment]
Can you tell me a little bit more about your system? operating system, compiler you're using, version of CMake that you were using before

**Comment by GiudGiud** [comment]
My workstation
Ubuntu 14.04 LTS
mpicc and mpif90 from gcc 4.8.4
cmake 2.8.12.2

NSE cluster
CentOS 6.3
mpicc and mpif90 from gcc 5.2.0
cmake 2.8.12.2 (have not updated so we can test fixes there)

**Comment by jtramm** [comment]
I ran into this issue as well when compiling on the JLSE login node. The listed fix changing the cmake_minimum_required(...) line work for me as well!

**Comment by paulromano** [comment]
I dug a little into this. It has to do with the C++ standard library not getting linked at link-time because the final step is to build a Fortran executable (main.F90). When minimum CMake is set as 2.8, `-lstdc++` appears on the link line and when the minimum is 2.8.12, it doesn't. I traced this down to a change in a CMake policy ([CMP0022](https://cmake.org/cmake/help/latest/policy/CMP0022.html)) but I'm not sure what the best resolution is. Another way to fix it is by reverting this policy (`cmake_policy(SET CMP0022 OLD)`) or by changing the `LINKER_LANGUAGE` to `CXX`.

**Comment by paulromano** [comment]
Our CMake minimum version (and our CMakeLists.txt file itself) has changed since the last update on this issue, so I'm going to go ahead and close this. Also, our `main()` is now in C++ so the issue might have solved itself. @GiudGiud If you are still seeing problems with CMake, feel free to reopen or post a new issue.
