### ISSUE TITLE
Multiple sources in openmc each source has its own flux

### ISSUE THREAD

**Issue by ABadea** [mit-crpg/openmc#999]
Dear All , 

how to make multiple sources in openmc each source has its own flux - ( number of  particles ) ?

**Comment by paulromano** [comment]
If you are using the Python API, you can simply assign multiple `openmc.Source` objects to the `openmc.Settings.source` attribute, e.g.,
```Python
src1 = openmc.Source(space=openmc.stats.Point(1., 0., 0.))
src2 = openmc.Source(space=openmc.stats.Point(-1., 0., 0.))
settings = openmc.Settings()
settings.source = [src1, src2]
...
```
Once the model is exported, this would appear in settings.xml as:
```xml
  <source strength="1.0">
    <space type="point">
      <parameters>1.0 0.0 0.0</parameters>
    </space>
  </source>
  <source strength="1.0">
    <space type="point">
      <parameters>-1.0 0.0 0.0</parameters>
    </space>
  </source>
```
Note that the source strength can be adjusted for each source as needed.

@ABadea These types of questions are better suited for the [openmc-users](https://groups.google.com/forum/#!forum/openmc-users) mailing list. Issues on github are generally reserved for bugs and feature requests rather than requests for assistance using the code. I'd encourage you to sign up for the mailing list and post any future inquiries there.
